-- 1 Update my account information except for the username.
--
-- (id, first_name, middle_name, last_name, SSN, birth_date, gender)
-- call updateStudent(6, 'Lithariel', 'Talion', 'Forgerizer', 121412, '1990-09-09', 'Female');
--
--
--
-- 2 View a list of courses’ names assigned to me based on my grade ordered by name.
--
-- (student_id)
-- call getMyCourses(1);
--
--
--
-- 3 Post questions I have about a certain course.
--
-- (student_id, course_id, title, question)
-- call insertQuestion(1, 1, "Apple pie exception", "I was making an apple pie when this error came out tried to pour some milk but it did not get solved");
--
--
--
-- 4 View all questions asked by other students on a certain course along with their answers.
--
-- (student_id, course_id)
-- call getQuestions(2, 1);
--
--
--
-- 5 View the assignments posted for the courses I take.
--
-- (student_id)
-- call getMyAssignments(1);
--
--
--
-- 6 Solve assignments posted for courses I take.
--
-- (student_id, assignment_id, solution)
-- call insertSolution(1, 1, "Donuts per second ma dear fellow");
--
--
--
-- 7 View the grade of the assignments I solved per course.
--
-- (student_id, course_id)
-- call getMyAssignments(1, 1);
--
--
--
-- 8 View the announcements posted within the past 10 days about the school I am enrolled in.
--
-- (student_id)
-- call getAnnouncements(1);
--
--
--
-- 9 View all the information about activities offered by my school, as well as the teacher responsible
-- for it.
--
-- (school_id)
-- call getActivities(1);
--
--
--
-- 10 Apply for activities in my school on the condition that I can not join two activities of the same
-- type on the same date.
--
-- (student_id, activity_id)
-- call joinActivity(1, 1);
--
--
--
-- 11 Join clubs offered by my school, if I am a highschool student.
--
-- (student_id, club_id)
-- call joinClub(1, 1);
--
--
--
-- 12 Search in a list of courses that i take by its name or code.
--
-- (student_id, name, code)
-- call searchCourses(1, 'Donuts', '101');
