-- call searchSchools("most","there","nat");
--
-- call getElementaryLevels();
--
-- call getMiddleLevels();
--
-- call getHighLevels();
--
-- call getSchoolReviews(1);
--
-- call getSchoolTeachers(1);
