use skool;

-- “As a system administrator, I should be able to ...”
--
-- Create a school with its information: school name, address, phone number, email, general information,
-- vision, mission, main language, type(national, international) and fees.
--
-- insert into schools(name, email, vision, mission, general_info, phone_number1 ,phone_number2, fees, address, main_language, type)
-- values("text", "hogdoor@hogdoor.com", "vision", "mission", "general_info", "012" ,"011", 5000, "right there", "English", "International");
--
--
--
-- Add courses to the system with all of its information: course code, course name, course level (elementary,
-- middle, high), grade, description and prerequisite course(s).
--
-- insert into courses(name, code, description, grade, level, teacher_id, school_id)
-- values("text", "code", "desc", 1, "Elementary Level", "012" ,"011", 5000, "right there", "English", "International");
--
-- insert into course_requires_course(course_id, req_course_id)
-- values(1,2);
--
--
--
-- Add admins to the system with their information: first name, middle name, last name, birthdate,
-- address, email, username, password, and gender. Given the school name, I should assign admins
-- to work in this school. Note that the salary of the admin depends on the type of the school. The
-- salary of an admin working in a national school is 3000 EGP, and that working in an international
-- school is 5000 EGP.
--
-- insert into users(username,password,role)
-- values("mcadmin","secret","Employee");
--
-- insert into employees(first_name, middle_name, last_name, role, birth_date, address, email, username, gender, school_id)
-- values("John", "Doe" , "McAdmin", "Admin", '1990-12-12', "Du, st, ft 1", "mcadmin@mcadmin.com", "mcadmin", "Male", 1);
--
-- insert into admins(salary, employee_id)
-- values(5000, 1);
--
--
--
-- Delete a school from the database with all of its corresponding information. Students and employees
-- of this school should not be deleted from the system, but should not have a username and password
-- on the system until they are assigned to a new school again.
--
-- delete from schools
-- where id = 1;
--
-- delete from users
-- where users.username in
-- select students.username
-- from students
-- where students.school_id = 1;
--
-- delete from users
-- where users.username in
-- select employees.username
-- from employees
-- where employees.school_id = 1;
--
