use trial;
create table schools (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `vision` mediumtext not null, `mission` mediumtext not null, `general_info` mediumtext not null, `phone_number1` varchar(255) not null, `phone_number2` varchar(255) null, `fees` int not null, `address` varchar(255) not null, `main_language` varchar(255) not null, `type` enum('National', 'International') not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table schools add unique `schools_email_unique`(`email`);
create table elementary_levels (`id` int unsigned not null auto_increment primary key, `supplies` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `school_id` int unsigned not null);
alter table elementary_levels add constraint `elementary_levels_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table elementary_levels add unique `elementary_levels_school_id_unique`(`school_id`);
create table middle_levels (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `school_id` int unsigned not null);
alter table middle_levels add constraint `middle_levels_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table middle_levels add unique `middle_levels_school_id_unique`(`school_id`);
create table high_levels (`id` int unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null, `school_id` int unsigned not null);
alter table high_levels add constraint `high_levels_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table high_levels add unique `high_levels_school_id_unique`(`school_id`);
create table clubs (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `purpose` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `high_level_id` int unsigned not null);
alter table clubs add constraint `clubs_high_level_id_foreign` foreign key (`high_level_id`) references `high_levels` (`id`) on delete cascade;
alter table clubs add index `clubs_high_level_id_index`(`high_level_id`);
create table users (`id` int unsigned not null auto_increment primary key, `username` varchar(255) not null, `password` varchar(255) not null, `role` enum('Parent', 'Student', 'Employee') not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table users add unique `users_username_unique`(`username`);
create table parents (`id` int unsigned not null auto_increment primary key, `first_name` varchar(255) not null, `middle_name` varchar(255) not null, `last_name` varchar(255) not null, `email` varchar(255) not null, `address` varchar(255) not null, `phone_number` varchar(255) not null, `mobile_number1` varchar(255) not null, `mobile_number2` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null, `username` varchar(255) not null);
alter table parents add constraint `parents_username_foreign` foreign key (`username`) references `users` (`username`) on delete cascade;
alter table parents add unique `parents_email_unique`(`email`);
alter table parents add unique `parents_username_unique`(`username`);
create table students (`id` int unsigned not null auto_increment primary key, `first_name` varchar(255) not null, `middle_name` varchar(255) not null, `last_name` varchar(255) not null, `email` varchar(255) not null, `SSN` int not null, `grade` int null, `gender` enum('Male', 'Female') not null, `birth_date` date not null, `created_at` timestamp null, `updated_at` timestamp null, `school_id` int unsigned null, `username` varchar(255) null);
alter table students add constraint `students_username_foreign` foreign key (`username`) references `users` (`username`) on delete set null;
alter table students add constraint `students_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete set null;
alter table students add unique `students_email_unique`(`email`);
alter table students add unique `students_ssn_unique`(`SSN`);
alter table students add index `students_school_id_index`(`school_id`);
alter table students add unique `students_username_unique`(`username`);
create table employees (`id` int unsigned not null auto_increment primary key, `first_name` varchar(255) not null, `middle_name` varchar(255) not null, `last_name` varchar(255) not null, `email` varchar(255) not null, `phone_number` varchar(255) not null, `mobile_number1` varchar(255) not null, `mobile_number2` varchar(255) not null, `address` varchar(255) not null, `role` enum('Admin', 'Teacher') not null, `gender` enum('Male', 'Female') not null, `birth_date` date not null, `created_at` timestamp null, `updated_at` timestamp null, `username` varchar(255) null, `school_id` int unsigned null);
alter table employees add constraint `employees_username_foreign` foreign key (`username`) references `users` (`username`) on delete set null;
alter table employees add constraint `employees_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete set null;
alter table employees add unique `employees_email_unique`(`email`);
alter table employees add unique `employees_username_unique`(`username`);
alter table employees add index `employees_school_id_index`(`school_id`);
create table club_joinedBy_student (`student_id` int unsigned not null, `club_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table club_joinedBy_student add primary key `club_joinedby_student_student_id_club_id_primary`(`student_id`, `club_id`);
alter table club_joinedBy_student add constraint `club_joinedby_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table club_joinedBy_student add constraint `club_joinedby_student_club_id_foreign` foreign key (`club_id`) references `clubs` (`id`) on delete cascade;
alter table club_joinedBy_student add index `club_joinedby_student_student_id_index`(`student_id`);
alter table club_joinedBy_student add index `club_joinedby_student_club_id_index`(`club_id`);
create table parent_has_student (`student_id` int unsigned not null, `parent_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table parent_has_student add primary key `parent_has_student_student_id_parent_id_primary`(`student_id`, `parent_id`);
alter table parent_has_student add constraint `parent_has_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table parent_has_student add constraint `parent_has_student_parent_id_foreign` foreign key (`parent_id`) references `parents` (`id`) on delete cascade;
alter table parent_has_student add index `parent_has_student_student_id_index`(`student_id`);
alter table parent_has_student add index `parent_has_student_parent_id_index`(`parent_id`);
create table teachers (`id` int unsigned not null auto_increment primary key, `years_of_exp` int not null, `salary` int not null, `created_at` timestamp null, `updated_at` timestamp null, `username` varchar(255) null, `supervisor_id` int unsigned null);
alter table teachers add constraint `teachers_username_foreign` foreign key (`username`) references `employees` (`username`) on delete cascade;
alter table teachers add unique `teachers_username_unique`(`username`);
alter table teachers add index `teachers_supervisor_id_index`(`supervisor_id`);
create table admins (`id` int unsigned not null auto_increment primary key, `salary` int not null, `username` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null);
alter table admins add constraint `admins_username_foreign` foreign key (`username`) references `employees` (`username`) on delete set null;
alter table admins add unique `admins_username_unique`(`username`);
create table courses (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `code` varchar(255) not null, `level` enum('Elementary Level', 'Middle Level', 'High Level') not null, `grade` int not null, `description` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `teacher_id` int unsigned not null, `school_id` int unsigned not null);
alter table courses add constraint `courses_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete cascade;
alter table courses add constraint `courses_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table courses add index `courses_teacher_id_index`(`teacher_id`);
alter table courses add index `courses_school_id_index`(`school_id`);
create table course_has_student (`course_id` int unsigned not null, `student_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table course_has_student add primary key `course_has_student_course_id_student_id_primary`(`course_id`, `student_id`);
alter table course_has_student add constraint `course_has_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table course_has_student add constraint `course_has_student_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
alter table course_has_student add index `course_has_student_course_id_index`(`course_id`);
alter table course_has_student add index `course_has_student_student_id_index`(`student_id`);
create table parent_reviews_school (`parent_id` int unsigned not null, `school_id` int unsigned not null, `review` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table parent_reviews_school add primary key `parent_reviews_school_school_id_parent_id_primary`(`school_id`, `parent_id`);
alter table parent_reviews_school add constraint `parent_reviews_school_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table parent_reviews_school add constraint `parent_reviews_school_parent_id_foreign` foreign key (`parent_id`) references `parents` (`id`) on delete cascade;
alter table parent_reviews_school add index `parent_reviews_school_parent_id_index`(`parent_id`);
alter table parent_reviews_school add index `parent_reviews_school_school_id_index`(`school_id`);
create table announcements (`id` int unsigned not null auto_increment primary key, `date` date not null, `description` mediumtext not null, `title` varchar(255) not null, `type` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null, `admin_id` int unsigned not null);
alter table announcements add constraint `announcements_admin_id_foreign` foreign key (`admin_id`) references `admins` (`id`);
alter table announcements add index `announcements_admin_id_index`(`admin_id`);
create table activities (`id` int unsigned not null auto_increment primary key, `date` date not null, `location` varchar(255) not null, `type` varchar(255) not null, `equipment` text not null, `description` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `teacher_id` int unsigned not null, `admin_id` int unsigned not null);
alter table activities add constraint `activities_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete cascade;
alter table activities add constraint `activities_admin_id_foreign` foreign key (`admin_id`) references `admins` (`id`) on delete cascade;
alter table activities add index `activities_teacher_id_index`(`teacher_id`);
alter table activities add index `activities_admin_id_index`(`admin_id`);
create table assignments (`id` int unsigned not null auto_increment primary key, `post_date` datetime not null, `due_date` datetime not null, `content` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `teacher_id` int unsigned not null, `course_id` int unsigned not null);
alter table assignments add constraint `assignments_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete cascade;
alter table assignments add constraint `assignments_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
alter table assignments add index `assignments_teacher_id_index`(`teacher_id`);
alter table assignments add index `assignments_course_id_index`(`course_id`);
create table assignment_solvedBy_student (`assignment_id` int unsigned not null, `student_id` int unsigned not null, `grade` int not null, `solution` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table assignment_solvedBy_student add primary key `assignment_solvedby_student_assignment_id_student_id_primary`(`assignment_id`, `student_id`);
alter table assignment_solvedBy_student add constraint `assignment_solvedby_student_assignment_id_foreign` foreign key (`assignment_id`) references `assignments` (`id`) on delete cascade;
alter table assignment_solvedBy_student add constraint `assignment_solvedby_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table assignment_solvedBy_student add index `assignment_solvedby_student_assignment_id_index`(`assignment_id`);
alter table assignment_solvedBy_student add index `assignment_solvedby_student_student_id_index`(`student_id`);
create table questions (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `question` mediumtext not null, `answer` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `student_id` int unsigned not null, `course_id` int unsigned not null, `teacher_id` int unsigned null);
alter table questions add constraint `questions_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
alter table questions add constraint `questions_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete set null;
alter table questions add constraint `questions_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table questions add index `questions_student_id_index`(`student_id`);
alter table questions add index `questions_course_id_index`(`course_id`);
alter table questions add index `questions_teacher_id_index`(`teacher_id`);
create table parent_rates_teacher (`parent_id` int unsigned not null, `teacher_id` int unsigned not null, `rate` int not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table parent_rates_teacher add primary key `parent_rates_teacher_parent_id_teacher_id_primary`(`parent_id`, `teacher_id`);
alter table parent_rates_teacher add constraint `parent_rates_teacher_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete cascade;
alter table parent_rates_teacher add constraint `parent_rates_teacher_parent_id_foreign` foreign key (`parent_id`) references `parents` (`id`) on delete cascade;
alter table parent_rates_teacher add index `parent_rates_teacher_parent_id_index`(`parent_id`);
alter table parent_rates_teacher add index `parent_rates_teacher_teacher_id_index`(`teacher_id`);
create table activity_joinedBy_student (`activity_id` int unsigned not null, `student_id` int unsigned not null, `accepted` enum('True', 'False', 'Pending') not null default 'Pending', `created_at` timestamp null, `updated_at` timestamp null);
alter table activity_joinedBy_student add primary key `activity_joinedby_student_activity_id_student_id_primary`(`activity_id`, `student_id`);
alter table activity_joinedBy_student add constraint `activity_joinedby_student_activity_id_foreign` foreign key (`activity_id`) references `activities` (`id`) on delete cascade;
alter table activity_joinedBy_student add constraint `activity_joinedby_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table activity_joinedBy_student add index `activity_joinedby_student_activity_id_index`(`activity_id`);
alter table activity_joinedBy_student add index `activity_joinedby_student_student_id_index`(`student_id`);
create table school_appliedBy_student (`school_id` int unsigned not null, `student_id` int unsigned not null, `accepted` enum('True', 'False', 'Pending') not null default 'Pending', `created_at` timestamp null, `updated_at` timestamp null, `parent_id` int unsigned null);
alter table school_appliedBy_student add primary key `school_appliedinby_student_school_id_student_id_primary`(`school_id`, `student_id`);
alter table school_appliedBy_student add constraint `school_appliedinby_student_school_id_foreign` foreign key (`school_id`) references `schools` (`id`) on delete cascade;
alter table school_appliedBy_student add constraint `school_appliedinby_student_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table school_appliedBy_student add constraint `school_appliedinby_student_parent_id_foreign` foreign key (`parent_id`) references `parents` (`id`) on delete set null;
alter table school_appliedBy_student add index `school_appliedinby_student_school_id_index`(`school_id`);
alter table school_appliedBy_student add index `school_appliedinby_student_student_id_index`(`student_id`);
alter table school_appliedBy_student add index `school_appliedinby_student_parent_id_index`(`parent_id`);
create table reports (`id` int unsigned not null auto_increment primary key, `report` mediumtext not null, `created_at` timestamp null, `updated_at` timestamp null, `teacher_id` int unsigned not null, `student_id` int unsigned not null);
alter table reports add constraint `reports_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade;
alter table reports add constraint `reports_teacher_id_foreign` foreign key (`teacher_id`) references `teachers` (`id`) on delete cascade;
alter table reports add index `reports_teacher_id_index`(`teacher_id`);
alter table reports add index `reports_student_id_index`(`student_id`);
create table parent_writes_report (`parent_id` int unsigned not null, `report_id` int unsigned not null, `teacher_comment` text not null, `parent_comment` text not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table parent_writes_report add primary key `parent_writes_report_report_id_parent_id_primary`(`report_id`, `parent_id`);
alter table parent_writes_report add constraint `parent_writes_report_report_id_foreign` foreign key (`report_id`) references `reports` (`id`) on delete cascade;
alter table parent_writes_report add constraint `parent_writes_report_parent_id_foreign` foreign key (`parent_id`) references `parents` (`id`) on delete cascade;
alter table parent_writes_report add index `parent_writes_report_parent_id_index`(`parent_id`);
alter table parent_writes_report add index `parent_writes_report_report_id_index`(`report_id`);
create table course_requires_course (`course_id` int unsigned not null, `req_course_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null);
alter table course_requires_course add primary key `course_requires_course_course_id_req_course_id_primary`(`course_id`, `req_course_id`);
alter table course_requires_course add constraint `course_requires_course_course_id_foreign` foreign key (`course_id`) references `courses` (`id`) on delete cascade;
alter table course_requires_course add constraint `course_requires_course_req_course_id_foreign` foreign key (`req_course_id`) references `courses` (`id`) on delete cascade;
